# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_task', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'answer_control_task',
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Answer_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('true_false', models.BooleanField()),
            ],
            options={
                'db_table': 'answer_test',
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043a \u0442\u0435\u0441\u0442\u0443',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043a \u0442\u0435\u0441\u0442\u0443',
            },
        ),
        migrations.CreateModel(
            name='Attempts_control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateTimeField(verbose_name='date task')),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'attempts_control_task',
                'verbose_name': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u043e\u0435 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Attempts_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateTimeField(verbose_name='date task')),
            ],
            options={
                'db_table': 'attempts_task',
                'verbose_name': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u043e\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Attempts_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateTimeField(verbose_name='date task')),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'attempts_test',
                'verbose_name': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0439 \u0442\u0435\u0441\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0435 \u0442\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Control_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_question', models.TextField()),
                ('step', models.IntegerField()),
            ],
            options={
                'db_table': 'control_question',
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
            ],
            options={
                'db_table': 'control_task',
                'verbose_name': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'course',
                'verbose_name': '\u041a\u0443\u0440\u0441',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('task', models.TextField()),
                ('answer_task', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'task',
                'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'test',
                'verbose_name': '\u0422\u0435\u0441\u0442',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Test_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Test')),
            ],
            options={
                'db_table': 'test_question',
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u043a \u0442\u0435\u0441\u0442\u0443',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043a \u0442\u0435\u0441\u0442\u0443',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.AddField(
            model_name='control_task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='control_question',
            name='control_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Control_task'),
        ),
        migrations.AddField(
            model_name='attempts_test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Test'),
        ),
        migrations.AddField(
            model_name='attempts_test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.User'),
        ),
        migrations.AddField(
            model_name='attempts_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Task'),
        ),
        migrations.AddField(
            model_name='attempts_task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.User'),
        ),
        migrations.AddField(
            model_name='attempts_control_task',
            name='control_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Control_task'),
        ),
        migrations.AddField(
            model_name='attempts_control_task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.User'),
        ),
        migrations.AddField(
            model_name='answer_test',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Test_question'),
        ),
        migrations.AddField(
            model_name='answer_control_task',
            name='control_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Control_question'),
        ),
    ]
