# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
