# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0008_auto_20170126_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('true_false', models.BooleanField()),
            ],
            options={
                'db_table': 'answer_test',
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043a \u0442\u0435\u0441\u0442\u0443',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043a \u0442\u0435\u0441\u0442\u0443',
            },
        ),
        migrations.CreateModel(
            name='Attempts_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateTimeField(verbose_name='date task')),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'attempts_test',
                'verbose_name': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0439 \u0442\u0435\u0441\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0435 \u0442\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Test_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
            options={
                'db_table': 'test_question',
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u043a \u0442\u0435\u0441\u0442\u0443',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043a \u0442\u0435\u0441\u0442\u0443',
            },
        ),
        migrations.CreateModel(
            name='Test_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'test_task',
                'verbose_name': '\u0422\u0435\u0441\u0442',
                'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='test_question',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.Test_task'),
        ),
        migrations.AddField(
            model_name='attempts_test',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.Test_task'),
        ),
        migrations.AddField(
            model_name='attempts_test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer_test',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.Test_question'),
        ),
    ]
