# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20170214_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_task', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'answer_control_task',
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Attempts_control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateTimeField(verbose_name='date task')),
            ],
            options={
                'db_table': 'attempts_control_task',
                'verbose_name': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u043e\u0435 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u043e\u0439\u0434\u0435\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Control_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_question', models.TextField()),
                ('step', models.IntegerField()),
            ],
            options={
                'db_table': 'control_question',
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043a \u043a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u043c\u0443 \u0437\u0434\u0430\u043d\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Control_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('theory', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'control_task',
                'verbose_name': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='control_question',
            name='control_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_task.Control_task'),
        ),
        migrations.AddField(
            model_name='attempts_control_task',
            name='control_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_task.Control_task'),
        ),
        migrations.AddField(
            model_name='attempts_control_task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer_control_task',
            name='control_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_task.Control_question'),
        ),
    ]
